-- Teaterstykker
INSERT INTO Teaterstykke (Tittel, Dramatiker) VALUES ('Kongsemnene', 'Henrik Ibsen');
INSERT INTO Teaterstykke (Tittel, Dramatiker) VALUES ('Størst av alt er kjærligheten', 'Jonas Corell Petersen');

-- Akt
INSERT INTO Akt (AktNr, Tittel, Navn) VALUES (1, 'Kongsemnene', NULL);
INSERT INTO Akt (AktNr, Tittel, Navn) VALUES (2, 'Kongsemnene', NULL);
INSERT INTO Akt (AktNr, Tittel, Navn) VALUES (3, 'Kongsemnene', NULL);
INSERT INTO Akt (AktNr, Tittel, Navn) VALUES (4, 'Kongsemnene', NULL);
INSERT INTO Akt (AktNr, Tittel, Navn) VALUES (5, 'Kongsemnene', NULL);

-- Skuespiller 
INSERT INTO Skuespiller (SkuespillerID, Fornavn, Etternavn) VALUES (1, 'Arturo', 'Scotti');
INSERT INTO Skuespiller (SkuespillerID, Fornavn, Etternavn) VALUES (2, 'Ingunn Beate', 'Stige Øyen');
INSERT INTO Skuespiller (SkuespillerID, Fornavn, Etternavn) VALUES (3, 'Hans Petter', 'Nilsen');
INSERT INTO Skuespiller (SkuespillerID, Fornavn, Etternavn) VALUES (4, 'Madeleine', 'Brandtzæg Nilsen');
INSERT INTO Skuespiller (SkuespillerID, Fornavn, Etternavn) VALUES (5, 'Synnøve', 'Fossum Eriksen');
INSERT INTO Skuespiller (SkuespillerID, Fornavn, Etternavn) VALUES (6, 'Emma Caroline', 'Deichmann');
INSERT INTO Skuespiller (SkuespillerID, Fornavn, Etternavn) VALUES (7, 'Thomas', 'Jensen Takyi');
INSERT INTO Skuespiller (SkuespillerID, Fornavn, Etternavn) VALUES (8, 'Per', 'Bogstad Gulliksen');
INSERT INTO Skuespiller (SkuespillerID, Fornavn, Etternavn) VALUES (9, 'Isak', 'Holmen Sørensen');
INSERT INTO Skuespiller (SkuespillerID, Fornavn, Etternavn) VALUES (10, 'Fabian', 'Heidelberg Lunde');
INSERT INTO Skuespiller (SkuespillerID, Fornavn, Etternavn) VALUES (11, 'Emil', 'Olafsson');
INSERT INTO Skuespiller (SkuespillerID, Fornavn, Etternavn) VALUES (12, 'Snorre', 'Ryen Tøndel');
INSERT INTO Skuespiller (SkuespillerID, Fornavn, Etternavn) VALUES (13, 'Sunniva', 'Du Mond Nordal');
INSERT INTO Skuespiller (SkuespillerID, Fornavn, Etternavn) VALUES (14, 'Jo', 'Saberniak');
INSERT INTO Skuespiller (SkuespillerID, Fornavn, Etternavn) VALUES (15, 'Marte', 'Steinholt');
INSERT INTO Skuespiller (SkuespillerID, Fornavn, Etternavn) VALUES (16, 'Tor Ivar', 'Hagen');
INSERT INTO Skuespiller (SkuespillerID, Fornavn, Etternavn) VALUES (17,'Trond-Ove', 'Skrødal');
INSERT INTO Skuespiller (SkuespillerID, Fornavn, Etternavn) VALUES (18, 'Natalie', 'Grøndahl Tangen');
INSERT INTO Skuespiller (SkuespillerID, Fornavn, Etternavn) VALUES (19, 'Åsmund', 'Flaten');


-- Rolle
INSERT INTO Rolle (RolleNavn, SkuespillerID) VALUES ('Håkon Håkonson', 1);
INSERT INTO Rolle (RolleNavn, SkuespillerID) VALUES ('Dagfinn Bonde', 11);
INSERT INTO Rolle (RolleNavn, SkuespillerID) VALUES ('Jatgeir Skald', 11);
INSERT INTO Rolle (RolleNavn, SkuespillerID) VALUES ('Sigrid', 6);
INSERT INTO Rolle (RolleNavn, SkuespillerID) VALUES ('Ingeborg', 6);
INSERT INTO Rolle (RolleNavn, SkuespillerID) VALUES ('Guttorm Ingesson', 8);
INSERT INTO Rolle (RolleNavn, SkuespillerID) VALUES ('Skule Jarl', 3);
INSERT INTO Rolle (RolleNavn, SkuespillerID) VALUES ('Inga frå Vartejg', 2);
INSERT INTO Rolle (RolleNavn, SkuespillerID) VALUES ('Paal Flida', 9);
INSERT INTO Rolle (RolleNavn, SkuespillerID) VALUES ('Ragnhild', 4);
INSERT INTO Rolle (RolleNavn, SkuespillerID) VALUES ('Gregorius Jonsson', 8);
INSERT INTO Rolle (RolleNavn, SkuespillerID) VALUES ('Margrete', 5);
INSERT INTO Rolle (RolleNavn, SkuespillerID) VALUES ('Biskop Nikolas', 7);
INSERT INTO Rolle (RolleNavn, SkuespillerID) VALUES ('Peter', 12);
INSERT INTO Rolle (RolleNavn, SkuespillerID) VALUES ('Sunniva Du Mond Nordal', 13);
INSERT INTO Rolle (RolleNavn, SkuespillerID) VALUES ('Jo Saberniak', 14);
INSERT INTO Rolle (RolleNavn, SkuespillerID) VALUES ('Marte Steinholt', 15);
INSERT INTO Rolle (RolleNavn, SkuespillerID) VALUES ('Tor Ivar Hagen', 16);
INSERT INTO Rolle (RolleNavn, SkuespillerID) VALUES ('Trond-Ove Skrødal', 17);
INSERT INTO Rolle (RolleNavn, SkuespillerID) VALUES ('Natalie Grøndahl Tangen', 18);
INSERT INTO Rolle (RolleNavn, SkuespillerID) VALUES ('Åsmund Flaten', 19);

-- AktRolleForhold
INSERT INTO AktRolleForhold (AktNr, Tittel, RolleNavn) VALUES (1, 'Kongsemnene', 'Håkon Håkonson');
INSERT INTO AktRolleForhold (AktNr, Tittel, RolleNavn) VALUES (1, 'Kongsemnene', 'Dagfinn Bonde');
INSERT INTO AktRolleForhold (AktNr, Tittel, RolleNavn) VALUES (1, 'Kongsemnene', 'Sigrid');
INSERT INTO AktRolleForhold (AktNr, Tittel, RolleNavn) VALUES (1, 'Kongsemnene', 'Skule Jarl');
INSERT INTO AktRolleForhold (AktNr, Tittel, RolleNavn) VALUES (1, 'Kongsemnene', 'Inga frå Vartejg');
INSERT INTO AktRolleForhold (AktNr, Tittel, RolleNavn) VALUES (1, 'Kongsemnene', 'Paal Flida');
INSERT INTO AktRolleForhold (AktNr, Tittel, RolleNavn) VALUES (1, 'Kongsemnene', 'Gregorius Jonsson');
INSERT INTO AktRolleForhold (AktNr, Tittel, RolleNavn) VALUES (1, 'Kongsemnene', 'Margrete');
INSERT INTO AktRolleForhold (AktNr, Tittel, RolleNavn) VALUES (1, 'Kongsemnene', 'Biskop Nikolas');
INSERT INTO AktRolleForhold (AktNr, Tittel, RolleNavn) VALUES (1, 'Kongsemnene', 'Skule Jarl');
INSERT INTO AktRolleForhold (AktNr, Tittel, RolleNavn) VALUES (1, 'Kongsemnene', 'Peter');
INSERT INTO AktRolleForhold (AktNr, Tittel, RolleNavn) VALUES (2, 'Kongsemnene', 'Håkon Håkonson');
INSERT INTO AktRolleForhold (AktNr, Tittel, RolleNavn) VALUES (2, 'Kongsemnene', 'Dagfinn Bonde');
INSERT INTO AktRolleForhold (AktNr, Tittel, RolleNavn) VALUES (2, 'Kongsemnene', 'Sigrid');
INSERT INTO AktRolleForhold (AktNr, Tittel, RolleNavn) VALUES (2, 'Kongsemnene', 'Skule Jarl');
INSERT INTO AktRolleForhold (AktNr, Tittel, RolleNavn) VALUES (2, 'Kongsemnene', 'Inga frå Vartejg');
INSERT INTO AktRolleForhold (AktNr, Tittel, RolleNavn) VALUES (2, 'Kongsemnene', 'Paal Flida');
INSERT INTO AktRolleForhold (AktNr, Tittel, RolleNavn) VALUES (2, 'Kongsemnene', 'Gregorius Jonsson');
INSERT INTO AktRolleForhold (AktNr, Tittel, RolleNavn) VALUES (2, 'Kongsemnene', 'Margrete');
INSERT INTO AktRolleForhold (AktNr, Tittel, RolleNavn) VALUES (2, 'Kongsemnene', 'Biskop Nikolas');
INSERT INTO AktRolleForhold (AktNr, Tittel, RolleNavn) VALUES (2, 'Kongsemnene', 'Peter');
INSERT INTO AktRolleForhold (AktNr, Tittel, RolleNavn) VALUES (3, 'Kongsemnene', 'Håkon Håkonson');
INSERT INTO AktRolleForhold (AktNr, Tittel, RolleNavn) VALUES (3, 'Kongsemnene', 'Dagfinn Bonde');
INSERT INTO AktRolleForhold (AktNr, Tittel, RolleNavn) VALUES (3, 'Kongsemnene', 'Skule Jarl');
INSERT INTO AktRolleForhold (AktNr, Tittel, RolleNavn) VALUES (3, 'Kongsemnene', 'Paal Flida');
INSERT INTO AktRolleForhold (AktNr, Tittel, RolleNavn) VALUES (3, 'Kongsemnene', 'Gregorius Jonsson');
INSERT INTO AktRolleForhold (AktNr, Tittel, RolleNavn) VALUES (3, 'Kongsemnene', 'Margrete');
INSERT INTO AktRolleForhold (AktNr, Tittel, RolleNavn) VALUES (4, 'Kongsemnene', 'Håkon Håkonson');
INSERT INTO AktRolleForhold (AktNr, Tittel, RolleNavn) VALUES (4, 'Kongsemnene', 'Dagfinn Bonde');
INSERT INTO AktRolleForhold (AktNr, Tittel, RolleNavn) VALUES (4, 'Kongsemnene', 'Jatgeir Skald');
INSERT INTO AktRolleForhold (AktNr, Tittel, RolleNavn) VALUES (4, 'Kongsemnene', 'Ingeborg');
INSERT INTO AktRolleForhold (AktNr, Tittel, RolleNavn) VALUES (4, 'Kongsemnene', 'Skule Jarl');
INSERT INTO AktRolleForhold (AktNr, Tittel, RolleNavn) VALUES (4, 'Kongsemnene', 'Paal Flida');
INSERT INTO AktRolleForhold (AktNr, Tittel, RolleNavn) VALUES (4, 'Kongsemnene', 'Gregorius Jonsson');
INSERT INTO AktRolleForhold (AktNr, Tittel, RolleNavn) VALUES (4, 'Kongsemnene', 'Margrete');
INSERT INTO AktRolleForhold (AktNr, Tittel, RolleNavn) VALUES (5, 'Kongsemnene', 'Håkon Håkonson');
INSERT INTO AktRolleForhold (AktNr, Tittel, RolleNavn) VALUES (5, 'Kongsemnene', 'Dagfinn Bonde');
INSERT INTO AktRolleForhold (AktNr, Tittel, RolleNavn) VALUES (5, 'Kongsemnene', 'Sigrid');
INSERT INTO AktRolleForhold (AktNr, Tittel, RolleNavn) VALUES (5, 'Kongsemnene', 'Paal Flida');
INSERT INTO AktRolleForhold (AktNr, Tittel, RolleNavn) VALUES (5, 'Kongsemnene', 'Ragnhild');
INSERT INTO AktRolleForhold (AktNr, Tittel, RolleNavn) VALUES (5, 'Kongsemnene', 'Gregorius Jonsson');
INSERT INTO AktRolleForhold (AktNr, Tittel, RolleNavn) VALUES (5, 'Kongsemnene', 'Margrete');
INSERT INTO AktRolleForhold (AktNr, Tittel, RolleNavn) VALUES (5, 'Kongsemnene', 'Biskop Nikolas');
INSERT INTO AktRolleForhold (AktNr, Tittel, RolleNavn) VALUES (5, 'Kongsemnene', 'Peter');


-- Kulisser
INSERT INTO Kulisser (KulissID, KulissType, Tittel) VALUES (NULL, NULL, NULL);

-- Ansatt
INSERT INTO Ansatt (AnsattID, Fornavn, Etternavn, Epost, AnsattStatus, AnsattType) VALUES (1, 'Yury', 'Butusov', NULL, 'Fast', 'Regissør');
INSERT INTO Ansatt (AnsattID, Fornavn, Etternavn, Epost, AnsattStatus, AnsattType) VALUES (2, 'Aleksandr', 'Shishkinhokusai', NULL, 'Fast', 'Scenograf');
INSERT INTO Ansatt (AnsattID, Fornavn, Etternavn, Epost, AnsattStatus, AnsattType) VALUES (3, 'Eivind', 'Myren', NULL, 'Fast', 'Lysdesigner');
INSERT INTO Ansatt (AnsattID, Fornavn, Etternavn, Epost, AnsattStatus, AnsattType) VALUES (4, 'Mina', 'Rype Stokke', NULL, 'Fast', 'Dramaturg');
INSERT INTO Ansatt (AnsattID, Fornavn, Etternavn, Epost, AnsattStatus, AnsattType) VALUES (5, 'Jonas', 'Corell Petersen', NULL, 'Fast', 'Regissør');
INSERT INTO Ansatt (AnsattID, Fornavn, Etternavn, Epost, AnsattStatus, AnsattType) VALUES (6, 'David', 'Gehrt', NULL, 'Fast', 'Scenograf');
INSERT INTO Ansatt (AnsattID, Fornavn, Etternavn, Epost, AnsattStatus, AnsattType) VALUES (7, 'Gaute', 'Tønder', NULL, 'Fast', 'Lyddesigner');
INSERT INTO Ansatt (AnsattID, Fornavn, Etternavn, Epost, AnsattStatus, AnsattType) VALUES (8, 'Magnus', 'Mikaelsen', NULL, 'Fast', 'Lysdesigner');
INSERT INTO Ansatt (AnsattID, Fornavn, Etternavn, Epost, AnsattStatus, AnsattType) VALUES (9, 'Kristoffer', 'Spender', NULL, 'Fast', 'Dramaturg');

-- JobberPå
INSERT INTO JobberPå (AnsattID, Tittel) VALUES (1, 'Kongsemnene');
INSERT INTO JobberPå (AnsattID, Tittel) VALUES (2, 'Kongsemnene');
INSERT INTO JobberPå (AnsattID, Tittel) VALUES (3, 'Kongsemnene');
INSERT INTO JobberPå (AnsattID, Tittel) VALUES (4, 'Kongsemnene');
INSERT INTO JobberPå (AnsattID, Tittel) VALUES (5, 'Størst av alt er kjærligheten');
INSERT INTO JobberPå (AnsattID, Tittel) VALUES (6, 'Størst av alt er kjærligheten');
INSERT INTO JobberPå (AnsattID, Tittel) VALUES (7, 'Størst av alt er kjærligheten');
INSERT INTO JobberPå (AnsattID, Tittel) VALUES (8, 'Størst av alt er kjærligheten');
INSERT INTO JobberPå (AnsattID, Tittel) VALUES (9, 'Størst av alt er kjærligheten');

-- Sal
INSERT INTO Sal (SalID, Navn, AntallPlasser) VALUES (1, 'Hovedscenen', 516);
INSERT INTO Sal (SalID, Navn, AntallPlasser) VALUES (2, 'Gamle scene', 332);
INSERT INTO Sal (SalID, Navn, AntallPlasser) VALUES (3, 'Studioscenen', 150);
INSERT INTO Sal (SalID, Navn, AntallPlasser) VALUES (4, 'Teaterscenen', 60);
INSERT INTO Sal (SalID, Navn, AntallPlasser) VALUES (5, 'Teaterkafeen', 100);


-- Fremvises
INSERT INTO Fremvises (Tittel, SalID) VALUES ('Kongsemnene', 1);
INSERT INTO Fremvises (Tittel, SalID) VALUES ('Størst av alt er kjærligheten', 2);


-- Forestillinger

-- Forestillinger for Kongsemnene
INSERT INTO Forestilling (Tittel, Dato, Starttid) VALUES ('Kongsemnene', '2024-02-01', '19:00:00');
INSERT INTO Forestilling (Tittel, Dato, Starttid) VALUES ('Kongsemnene', '2024-02-02', '19:00:00');
INSERT INTO Forestilling (Tittel, Dato, Starttid) VALUES ('Kongsemnene', '2024-02-03', '19:00:00');
INSERT INTO Forestilling (Tittel, Dato, Starttid) VALUES ('Kongsemnene', '2024-02-05', '19:00:00');
INSERT INTO Forestilling (Tittel, Dato, Starttid) VALUES ('Kongsemnene', '2024-02-06', '19:00:00');

-- Forestillinger for Størst av alt er kjærligheten
INSERT INTO Forestilling (Tittel, Dato, Starttid) VALUES ('Størst av alt er kjærligheten', '2024-02-03', '18:30:00');
INSERT INTO Forestilling (Tittel, Dato, Starttid) VALUES ('Størst av alt er kjærligheten', '2024-02-06', '18:30:00');
INSERT INTO Forestilling (Tittel, Dato, Starttid) VALUES ('Størst av alt er kjærligheten', '2024-02-07', '18:30:00');
INSERT INTO Forestilling (Tittel, Dato, Starttid) VALUES ('Størst av alt er kjærligheten', '2024-02-12', '18:30:00');
INSERT INTO Forestilling (Tittel, Dato, Starttid) VALUES ('Størst av alt er kjærligheten', '2024-02-13', '18:30:00');
INSERT INTO Forestilling (Tittel, Dato, Starttid) VALUES ('Størst av alt er kjærligheten', '2024-02-14', '18:30:00');

-- Stol
INSERT INTO Stol (StolID, StolNr, RadNr, Område, SalID) VALUES (1, 1, 1, 'Parkett', 2);
INSERT INTO Stol (StolID, StolNr, RadNr, Område, SalID) VALUES (2, 2, 1, 'Parkett', 2);
INSERT INTO Stol (StolID, StolNr, RadNr, Område, SalID) VALUES (3, 3, 1, 'Parkett', 2);
INSERT INTO Stol (StolID, StolNr, RadNr, Område, SalID) VALUES (4, 4, 1, 'Parkett', 2);
INSERT INTO Stol (StolID, StolNr, RadNr, Område, SalID) VALUES (5, 5, 1, 'Parkett', 2);
INSERT INTO Stol (StolID, StolNr, RadNr, Område, SalID) VALUES (6, 6, 1, 'Parkett', 2);
INSERT INTO Stol (StolID, StolNr, RadNr, Område, SalID) VALUES (7, 7, 1, 'Parkett', 2);
INSERT INTO Stol (StolID, StolNr, RadNr, Område, SalID) VALUES (8, 8, 1, 'Parkett', 2);
INSERT INTO Stol (StolID, StolNr, RadNr, Område, SalID) VALUES (9, 9, 1, 'Parkett', 2);
INSERT INTO Stol (StolID, StolNr, RadNr, Område, SalID) VALUES (10, 10, 1, 'Parkett', 2);
INSERT INTO Stol (StolID, StolNr, RadNr, Område, SalID) VALUES (11, 11, 1, 'Parkett', 2);
INSERT INTO Stol (StolID, StolNr, RadNr, Område, SalID) VALUES (12, 12, 1, 'Parkett', 2);
INSERT INTO Stol (StolID, StolNr, RadNr, Område, SalID) VALUES (13, 13, 1, 'Parkett', 2);
INSERT INTO Stol (StolID, StolNr, RadNr, Område, SalID) VALUES (14, 14, 1, 'Parkett', 2);
INSERT INTO Stol (StolID, StolNr, RadNr, Område, SalID) VALUES (15, 15, 1, 'Parkett', 2);
INSERT INTO Stol (StolID, StolNr, RadNr, Område, SalID) VALUES (16, 16, 1, 'Parkett', 2);
INSERT INTO Stol (StolID, StolNr, RadNr, Område, SalID) VALUES (17, 17, 1, 'Parkett', 2);
INSERT INTO Stol (StolID, StolNr, RadNr, Område, SalID) VALUES (18, 18, 1, 'Parkett', 2);
INSERT INTO Stol (StolID, StolNr, RadNr, Område, SalID) VALUES (19, 1, 2, 'Parkett', 2);
INSERT INTO Stol (StolID, StolNr, RadNr, Område, SalID) VALUES (20, 2, 2, 'Parkett', 2);
INSERT INTO Stol (StolID, StolNr, RadNr, Område, SalID) VALUES (21, 3, 2, 'Parkett', 2);
INSERT INTO Stol (StolID, StolNr, RadNr, Område, SalID) VALUES (22, 4, 2, 'Parkett', 2);
INSERT INTO Stol (StolID, StolNr, RadNr, Område, SalID) VALUES (23, 5, 2, 'Parkett', 2);
INSERT INTO Stol (StolID, StolNr, RadNr, Område, SalID) VALUES (24, 6, 2, 'Parkett', 2);
INSERT INTO Stol (StolID, StolNr, RadNr, Område, SalID) VALUES (25, 7, 2, 'Parkett', 2);
INSERT INTO Stol (StolID, StolNr, RadNr, Område, SalID) VALUES (26, 8, 2, 'Parkett', 2);
INSERT INTO Stol (StolID, StolNr, RadNr, Område, SalID) VALUES (27, 9, 2, 'Parkett', 2);
INSERT INTO Stol (StolID, StolNr, RadNr, Område, SalID) VALUES (28, 10, 2, 'Parkett', 2);
INSERT INTO Stol (StolID, StolNr, RadNr, Område, SalID) VALUES (29, 11, 2, 'Parkett', 2);
INSERT INTO Stol (StolID, StolNr, RadNr, Område, SalID) VALUES (30, 12, 2, 'Parkett', 2);
INSERT INTO Stol (StolID, StolNr, RadNr, Område, SalID) VALUES (31, 13, 2, 'Parkett', 2);
INSERT INTO Stol (StolID, StolNr, RadNr, Område, SalID) VALUES (32, 14, 2, 'Parkett', 2);
INSERT INTO Stol (StolID, StolNr, RadNr, Område, SalID) VALUES (33, 15, 2, 'Parkett', 2);
INSERT INTO Stol (StolID, StolNr, RadNr, Område, SalID) VALUES (34, 16, 2, 'Parkett', 2);
INSERT INTO Stol (StolID, StolNr, RadNr, Område, SalID) VALUES (35, 1, 3, 'Parkett', 2);
INSERT INTO Stol (StolID, StolNr, RadNr, Område, SalID) VALUES (36, 2, 3, 'Parkett', 2);
INSERT INTO Stol (StolID, StolNr, RadNr, Område, SalID) VALUES (37, 3, 3, 'Parkett', 2);
INSERT INTO Stol (StolID, StolNr, RadNr, Område, SalID) VALUES (38, 4, 3, 'Parkett', 2);
INSERT INTO Stol (StolID, StolNr, RadNr, Område, SalID) VALUES (39, 5, 3, 'Parkett', 2);
INSERT INTO Stol (StolID, StolNr, RadNr, Område, SalID) VALUES (40, 6, 3, 'Parkett', 2);
INSERT INTO Stol (StolID, StolNr, RadNr, Område, SalID) VALUES (41, 7, 3, 'Parkett', 2);
INSERT INTO Stol (StolID, StolNr, RadNr, Område, SalID) VALUES (42, 8, 3, 'Parkett', 2);
INSERT INTO Stol (StolID, StolNr, RadNr, Område, SalID) VALUES (43, 9, 3, 'Parkett', 2);
INSERT INTO Stol (StolID, StolNr, RadNr, Område, SalID) VALUES (44, 10, 3, 'Parkett', 2);
INSERT INTO Stol (StolID, StolNr, RadNr, Område, SalID) VALUES (45, 11, 3, 'Parkett', 2);
INSERT INTO Stol (StolID, StolNr, RadNr, Område, SalID) VALUES (46, 12, 3, 'Parkett', 2);
INSERT INTO Stol (StolID, StolNr, RadNr, Område, SalID) VALUES (47, 13, 3, 'Parkett', 2);
INSERT INTO Stol (StolID, StolNr, RadNr, Område, SalID) VALUES (48, 14, 3, 'Parkett', 2);
INSERT INTO Stol (StolID, StolNr, RadNr, Område, SalID) VALUES (49, 15, 3, 'Parkett', 2);
INSERT INTO Stol (StolID, StolNr, RadNr, Område, SalID) VALUES (50, 16, 3, 'Parkett', 2);
INSERT INTO Stol (StolID, StolNr, RadNr, Område, SalID) VALUES (51, 17, 3, 'Parkett', 2);
INSERT INTO Stol (StolID, StolNr, RadNr, Område, SalID) VALUES (52, 1, 4, 'Parkett', 2);
INSERT INTO Stol (StolID, StolNr, RadNr, Område, SalID) VALUES (53, 2, 4, 'Parkett', 2);
INSERT INTO Stol (StolID, StolNr, RadNr, Område, SalID) VALUES (54, 3, 4, 'Parkett', 2);
INSERT INTO Stol (StolID, StolNr, RadNr, Område, SalID) VALUES (55, 4, 4, 'Parkett', 2);
INSERT INTO Stol (StolID, StolNr, RadNr, Område, SalID) VALUES (56, 5, 4, 'Parkett', 2);
INSERT INTO Stol (StolID, StolNr, RadNr, Område, SalID) VALUES (57, 6, 4, 'Parkett', 2);
INSERT INTO Stol (StolID, StolNr, RadNr, Område, SalID) VALUES (58, 7, 4, 'Parkett', 2);
INSERT INTO Stol (StolID, StolNr, RadNr, Område, SalID) VALUES (59, 8, 4, 'Parkett', 2);
INSERT INTO Stol (StolID, StolNr, RadNr, Område, SalID) VALUES (60, 9, 4, 'Parkett', 2);
INSERT INTO Stol (StolID, StolNr, RadNr, Område, SalID) VALUES (61, 10, 4, 'Parkett', 2);
INSERT INTO Stol (StolID, StolNr, RadNr, Område, SalID) VALUES (62, 11, 4, 'Parkett', 2);
INSERT INTO Stol (StolID, StolNr, RadNr, Område, SalID) VALUES (63, 12, 4, 'Parkett', 2);
INSERT INTO Stol (StolID, StolNr, RadNr, Område, SalID) VALUES (64, 13, 4, 'Parkett', 2);
INSERT INTO Stol (StolID, StolNr, RadNr, Område, SalID) VALUES (65, 14, 4, 'Parkett', 2);
INSERT INTO Stol (StolID, StolNr, RadNr, Område, SalID) VALUES (66, 15, 4, 'Parkett', 2);
INSERT INTO Stol (StolID, StolNr, RadNr, Område, SalID) VALUES (67, 16, 4, 'Parkett', 2);
INSERT INTO Stol (StolID, StolNr, RadNr, Område, SalID) VALUES (68, 17, 4, 'Parkett', 2);
INSERT INTO Stol (StolID, StolNr, RadNr, Område, SalID) VALUES (69, 18, 4, 'Parkett', 2);
INSERT INTO Stol (StolID, StolNr, RadNr, Område, SalID) VALUES (70, 1, 5, 'Parkett', 2);
INSERT INTO Stol (StolID, StolNr, RadNr, Område, SalID) VALUES (71, 2, 5, 'Parkett', 2);
INSERT INTO Stol (StolID, StolNr, RadNr, Område, SalID) VALUES (72, 3, 5, 'Parkett', 2);
INSERT INTO Stol (StolID, StolNr, RadNr, Område, SalID) VALUES (73, 4, 5, 'Parkett', 2);
INSERT INTO Stol (StolID, StolNr, RadNr, Område, SalID) VALUES (74, 5, 5, 'Parkett', 2);
INSERT INTO Stol (StolID, StolNr, RadNr, Område, SalID) VALUES (75, 6, 5, 'Parkett', 2);
INSERT INTO Stol (StolID, StolNr, RadNr, Område, SalID) VALUES (76, 7, 5, 'Parkett', 2);
INSERT INTO Stol (StolID, StolNr, RadNr, Område, SalID) VALUES (77, 8, 5, 'Parkett', 2);
INSERT INTO Stol (StolID, StolNr, RadNr, Område, SalID) VALUES (78, 9, 5, 'Parkett', 2);
INSERT INTO Stol (StolID, StolNr, RadNr, Område, SalID) VALUES (79, 10, 5, 'Parkett', 2);
INSERT INTO Stol (StolID, StolNr, RadNr, Område, SalID) VALUES (80, 11, 5, 'Parkett', 2);
INSERT INTO Stol (StolID, StolNr, RadNr, Område, SalID) VALUES (81, 12, 5, 'Parkett', 2);
INSERT INTO Stol (StolID, StolNr, RadNr, Område, SalID) VALUES (82, 13, 5, 'Parkett', 2);
INSERT INTO Stol (StolID, StolNr, RadNr, Område, SalID) VALUES (83, 14, 5, 'Parkett', 2);
INSERT INTO Stol (StolID, StolNr, RadNr, Område, SalID) VALUES (84, 15, 5, 'Parkett', 2);
INSERT INTO Stol (StolID, StolNr, RadNr, Område, SalID) VALUES (85, 16, 5, 'Parkett', 2);
INSERT INTO Stol (StolID, StolNr, RadNr, Område, SalID) VALUES (86, 17, 5, 'Parkett', 2);
INSERT INTO Stol (StolID, StolNr, RadNr, Område, SalID) VALUES (87, 18, 5, 'Parkett', 2);
INSERT INTO Stol (StolID, StolNr, RadNr, Område, SalID) VALUES (88, 1, 6, 'Parkett', 2);
INSERT INTO Stol (StolID, StolNr, RadNr, Område, SalID) VALUES (89, 2, 6, 'Parkett', 2);
INSERT INTO Stol (StolID, StolNr, RadNr, Område, SalID) VALUES (90, 3, 6, 'Parkett', 2);
INSERT INTO Stol (StolID, StolNr, RadNr, Område, SalID) VALUES (91, 4, 6, 'Parkett', 2);
INSERT INTO Stol (StolID, StolNr, RadNr, Område, SalID) VALUES (92, 5, 6, 'Parkett', 2);
INSERT INTO Stol (StolID, StolNr, RadNr, Område, SalID) VALUES (93, 6, 6, 'Parkett', 2);
INSERT INTO Stol (StolID, StolNr, RadNr, Område, SalID) VALUES (94, 7, 6, 'Parkett', 2);
INSERT INTO Stol (StolID, StolNr, RadNr, Område, SalID) VALUES (95, 8, 6, 'Parkett', 2);
INSERT INTO Stol (StolID, StolNr, RadNr, Område, SalID) VALUES (96, 9, 6, 'Parkett', 2);
INSERT INTO Stol (StolID, StolNr, RadNr, Område, SalID) VALUES (97, 10, 6, 'Parkett', 2);
INSERT INTO Stol (StolID, StolNr, RadNr, Område, SalID) VALUES (98, 11, 6, 'Parkett', 2);
INSERT INTO Stol (StolID, StolNr, RadNr, Område, SalID) VALUES (99, 12, 6, 'Parkett', 2);
INSERT INTO Stol (StolID, StolNr, RadNr, Område, SalID) VALUES (100, 13, 6, 'Parkett', 2);
INSERT INTO Stol (StolID, StolNr, RadNr, Område, SalID) VALUES (101, 14, 6, 'Parkett', 2);
INSERT INTO Stol (StolID, StolNr, RadNr, Område, SalID) VALUES (102, 15, 6, 'Parkett', 2);
INSERT INTO Stol (StolID, StolNr, RadNr, Område, SalID) VALUES (103, 16, 6, 'Parkett', 2);
INSERT INTO Stol (StolID, StolNr, RadNr, Område, SalID) VALUES (104, 17, 6, 'Parkett', 2);
INSERT INTO Stol (StolID, StolNr, RadNr, Område, SalID) VALUES (105, 1, 7, 'Parkett', 2);
INSERT INTO Stol (StolID, StolNr, RadNr, Område, SalID) VALUES (106, 2, 7, 'Parkett', 2);
INSERT INTO Stol (StolID, StolNr, RadNr, Område, SalID) VALUES (107, 3, 7, 'Parkett', 2);
INSERT INTO Stol (StolID, StolNr, RadNr, Område, SalID) VALUES (108, 4, 7, 'Parkett', 2);
INSERT INTO Stol (StolID, StolNr, RadNr, Område, SalID) VALUES (109, 5, 7, 'Parkett', 2);
INSERT INTO Stol (StolID, StolNr, RadNr, Område, SalID) VALUES (110, 6, 7, 'Parkett', 2);
INSERT INTO Stol (StolID, StolNr, RadNr, Område, SalID) VALUES (111, 7, 7, 'Parkett', 2);
INSERT INTO Stol (StolID, StolNr, RadNr, Område, SalID) VALUES (112, 8, 7, 'Parkett', 2);
INSERT INTO Stol (StolID, StolNr, RadNr, Område, SalID) VALUES (113, 9, 7, 'Parkett', 2);
INSERT INTO Stol (StolID, StolNr, RadNr, Område, SalID) VALUES (114, 10, 7, 'Parkett', 2);
INSERT INTO Stol (StolID, StolNr, RadNr, Område, SalID) VALUES (115, 11, 7, 'Parkett', 2);
INSERT INTO Stol (StolID, StolNr, RadNr, Område, SalID) VALUES (116, 12, 7, 'Parkett', 2);
INSERT INTO Stol (StolID, StolNr, RadNr, Område, SalID) VALUES (117, 13, 7, 'Parkett', 2);
INSERT INTO Stol (StolID, StolNr, RadNr, Område, SalID) VALUES (118, 14, 7, 'Parkett', 2);
INSERT INTO Stol (StolID, StolNr, RadNr, Område, SalID) VALUES (119, 15, 7, 'Parkett', 2);
INSERT INTO Stol (StolID, StolNr, RadNr, Område, SalID) VALUES (120, 16, 7, 'Parkett', 2);
INSERT INTO Stol (StolID, StolNr, RadNr, Område, SalID) VALUES (121, 17, 7, 'Parkett', 2);
INSERT INTO Stol (StolID, StolNr, RadNr, Område, SalID) VALUES (122, 18, 7, 'Parkett', 2);
INSERT INTO Stol (StolID, StolNr, RadNr, Område, SalID) VALUES (123, 1, 8, 'Parkett', 2);
INSERT INTO Stol (StolID, StolNr, RadNr, Område, SalID) VALUES (124, 2, 8, 'Parkett', 2);
INSERT INTO Stol (StolID, StolNr, RadNr, Område, SalID) VALUES (125, 3, 8, 'Parkett', 2);
INSERT INTO Stol (StolID, StolNr, RadNr, Område, SalID) VALUES (126, 4, 8, 'Parkett', 2);
INSERT INTO Stol (StolID, StolNr, RadNr, Område, SalID) VALUES (127, 5, 8, 'Parkett', 2);
INSERT INTO Stol (StolID, StolNr, RadNr, Område, SalID) VALUES (128, 6, 8, 'Parkett', 2);
INSERT INTO Stol (StolID, StolNr, RadNr, Område, SalID) VALUES (129, 7, 8, 'Parkett', 2);
INSERT INTO Stol (StolID, StolNr, RadNr, Område, SalID) VALUES (130, 8, 8, 'Parkett', 2);
INSERT INTO Stol (StolID, StolNr, RadNr, Område, SalID) VALUES (131, 9, 8, 'Parkett', 2);
INSERT INTO Stol (StolID, StolNr, RadNr, Område, SalID) VALUES (132, 10, 8, 'Parkett', 2);
INSERT INTO Stol (StolID, StolNr, RadNr, Område, SalID) VALUES (133, 11, 8, 'Parkett', 2);
INSERT INTO Stol (StolID, StolNr, RadNr, Område, SalID) VALUES (134, 12, 8, 'Parkett', 2);
INSERT INTO Stol (StolID, StolNr, RadNr, Område, SalID) VALUES (135, 13, 8, 'Parkett', 2);
INSERT INTO Stol (StolID, StolNr, RadNr, Område, SalID) VALUES (136, 14, 8, 'Parkett', 2);
INSERT INTO Stol (StolID, StolNr, RadNr, Område, SalID) VALUES (137, 15, 8, 'Parkett', 2);
INSERT INTO Stol (StolID, StolNr, RadNr, Område, SalID) VALUES (138, 16, 8, 'Parkett', 2);
INSERT INTO Stol (StolID, StolNr, RadNr, Område, SalID) VALUES (139, 17, 8, 'Parkett', 2);
INSERT INTO Stol (StolID, StolNr, RadNr, Område, SalID) VALUES (140, 1, 9, 'Parkett', 2);
INSERT INTO Stol (StolID, StolNr, RadNr, Område, SalID) VALUES (141, 2, 9, 'Parkett', 2);
INSERT INTO Stol (StolID, StolNr, RadNr, Område, SalID) VALUES (142, 3, 9, 'Parkett', 2);
INSERT INTO Stol (StolID, StolNr, RadNr, Område, SalID) VALUES (143, 4, 9, 'Parkett', 2);
INSERT INTO Stol (StolID, StolNr, RadNr, Område, SalID) VALUES (144, 5, 9, 'Parkett', 2);
INSERT INTO Stol (StolID, StolNr, RadNr, Område, SalID) VALUES (145, 6, 9, 'Parkett', 2);
INSERT INTO Stol (StolID, StolNr, RadNr, Område, SalID) VALUES (146, 7, 9, 'Parkett', 2);
INSERT INTO Stol (StolID, StolNr, RadNr, Område, SalID) VALUES (147, 8, 9, 'Parkett', 2);
INSERT INTO Stol (StolID, StolNr, RadNr, Område, SalID) VALUES (148, 9, 9, 'Parkett', 2);
INSERT INTO Stol (StolID, StolNr, RadNr, Område, SalID) VALUES (149, 10, 9, 'Parkett', 2);
INSERT INTO Stol (StolID, StolNr, RadNr, Område, SalID) VALUES (150, 11, 9, 'Parkett', 2);
INSERT INTO Stol (StolID, StolNr, RadNr, Område, SalID) VALUES (151, 12, 9, 'Parkett', 2);
INSERT INTO Stol (StolID, StolNr, RadNr, Område, SalID) VALUES (152, 13, 9, 'Parkett', 2);
INSERT INTO Stol (StolID, StolNr, RadNr, Område, SalID) VALUES (153, 14, 9, 'Parkett', 2);
INSERT INTO Stol (StolID, StolNr, RadNr, Område, SalID) VALUES (154, 15, 9, 'Parkett', 2);
INSERT INTO Stol (StolID, StolNr, RadNr, Område, SalID) VALUES (155, 16, 9, 'Parkett', 2);
INSERT INTO Stol (StolID, StolNr, RadNr, Område, SalID) VALUES (156, 17, 9, 'Parkett', 2);
INSERT INTO Stol (StolID, StolNr, RadNr, Område, SalID) VALUES (157, 1, 10, 'Parkett', 2);
INSERT INTO Stol (StolID, StolNr, RadNr, Område, SalID) VALUES (158, 2, 10, 'Parkett', 2);
INSERT INTO Stol (StolID, StolNr, RadNr, Område, SalID) VALUES (159, 3, 10, 'Parkett', 2);
INSERT INTO Stol (StolID, StolNr, RadNr, Område, SalID) VALUES (160, 4, 10, 'Parkett', 2);
INSERT INTO Stol (StolID, StolNr, RadNr, Område, SalID) VALUES (161, 5, 10, 'Parkett', 2);
INSERT INTO Stol (StolID, StolNr, RadNr, Område, SalID) VALUES (162, 6, 10, 'Parkett', 2);
INSERT INTO Stol (StolID, StolNr, RadNr, Område, SalID) VALUES (163, 7, 10, 'Parkett', 2);
INSERT INTO Stol (StolID, StolNr, RadNr, Område, SalID) VALUES (164, 8, 10, 'Parkett', 2);
INSERT INTO Stol (StolID, StolNr, RadNr, Område, SalID) VALUES (165, 9, 10, 'Parkett', 2);
INSERT INTO Stol (StolID, StolNr, RadNr, Område, SalID) VALUES (166, 10, 10, 'Parkett', 2);
INSERT INTO Stol (StolID, StolNr, RadNr, Område, SalID) VALUES (167, 11, 10, 'Parkett', 2);
INSERT INTO Stol (StolID, StolNr, RadNr, Område, SalID) VALUES (168, 12, 10, 'Parkett', 2);
INSERT INTO Stol (StolID, StolNr, RadNr, Område, SalID) VALUES (169, 13, 10, 'Parkett', 2);
INSERT INTO Stol (StolID, StolNr, RadNr, Område, SalID) VALUES (170, 14, 10, 'Parkett', 2);


INSERT INTO Stol (StolID, StolNr, RadNr, Område, SalID) VALUES (171, 1, 1, 'Balkong', 2);
INSERT INTO Stol (StolID, StolNr, RadNr, Område, SalID) VALUES (172, 2, 1, 'Balkong', 2);
INSERT INTO Stol (StolID, StolNr, RadNr, Område, SalID) VALUES (173, 3, 1, 'Balkong', 2);
INSERT INTO Stol (StolID, StolNr, RadNr, Område, SalID) VALUES (174, 4, 1, 'Balkong', 2);
INSERT INTO Stol (StolID, StolNr, RadNr, Område, SalID) VALUES (175, 5, 1, 'Balkong', 2);
INSERT INTO Stol (StolID, StolNr, RadNr, Område, SalID) VALUES (176, 6, 1, 'Balkong', 2);
INSERT INTO Stol (StolID, StolNr, RadNr, Område, SalID) VALUES (177, 7, 1, 'Balkong', 2);
INSERT INTO Stol (StolID, StolNr, RadNr, Område, SalID) VALUES (178, 8, 1, 'Balkong', 2);
INSERT INTO Stol (StolID, StolNr, RadNr, Område, SalID) VALUES (179, 9, 1, 'Balkong', 2);
INSERT INTO Stol (StolID, StolNr, RadNr, Område, SalID) VALUES (180, 10, 1, 'Balkong', 2);
INSERT INTO Stol (StolID, StolNr, RadNr, Område, SalID) VALUES (181, 11, 1, 'Balkong', 2);
INSERT INTO Stol (StolID, StolNr, RadNr, Område, SalID) VALUES (182, 12, 1, 'Balkong', 2);
INSERT INTO Stol (StolID, StolNr, RadNr, Område, SalID) VALUES (183, 13, 1, 'Balkong', 2);
INSERT INTO Stol (StolID, StolNr, RadNr, Område, SalID) VALUES (184, 14, 1, 'Balkong', 2);
INSERT INTO Stol (StolID, StolNr, RadNr, Område, SalID) VALUES (185, 15, 1, 'Balkong', 2);
INSERT INTO Stol (StolID, StolNr, RadNr, Område, SalID) VALUES (186, 16, 1, 'Balkong', 2);
INSERT INTO Stol (StolID, StolNr, RadNr, Område, SalID) VALUES (187, 17, 1, 'Balkong', 2);
INSERT INTO Stol (StolID, StolNr, RadNr, Område, SalID) VALUES (188, 18, 1, 'Balkong', 2);
INSERT INTO Stol (StolID, StolNr, RadNr, Område, SalID) VALUES (189, 19, 1, 'Balkong', 2);
INSERT INTO Stol (StolID, StolNr, RadNr, Område, SalID) VALUES (190, 20, 1, 'Balkong', 2);
INSERT INTO Stol (StolID, StolNr, RadNr, Område, SalID) VALUES (191, 21, 1, 'Balkong', 2);
INSERT INTO Stol (StolID, StolNr, RadNr, Område, SalID) VALUES (192, 22, 1, 'Balkong', 2);
INSERT INTO Stol (StolID, StolNr, RadNr, Område, SalID) VALUES (193, 23, 1, 'Balkong', 2);
INSERT INTO Stol (StolID, StolNr, RadNr, Område, SalID) VALUES (194, 24, 1, 'Balkong', 2);
INSERT INTO Stol (StolID, StolNr, RadNr, Område, SalID) VALUES (195, 25, 1, 'Balkong', 2);
INSERT INTO Stol (StolID, StolNr, RadNr, Område, SalID) VALUES (196, 26, 1, 'Balkong', 2);
INSERT INTO Stol (StolID, StolNr, RadNr, Område, SalID) VALUES (197, 27, 1, 'Balkong', 2);
INSERT INTO Stol (StolID, StolNr, RadNr, Område, SalID) VALUES (198, 28, 1, 'Balkong', 2);
INSERT INTO Stol (StolID, StolNr, RadNr, Område, SalID) VALUES (199, 1, 2, 'Balkong', 2);
INSERT INTO Stol (StolID, StolNr, RadNr, Område, SalID) VALUES (200, 2, 2, 'Balkong', 2);
INSERT INTO Stol (StolID, StolNr, RadNr, Område, SalID) VALUES (201, 3, 2, 'Balkong', 2);
INSERT INTO Stol (StolID, StolNr, RadNr, Område, SalID) VALUES (202, 4, 2, 'Balkong', 2);
INSERT INTO Stol (StolID, StolNr, RadNr, Område, SalID) VALUES (203, 5, 2, 'Balkong', 2);
INSERT INTO Stol (StolID, StolNr, RadNr, Område, SalID) VALUES (204, 6, 2, 'Balkong', 2);
INSERT INTO Stol (StolID, StolNr, RadNr, Område, SalID) VALUES (205, 7, 2, 'Balkong', 2);
INSERT INTO Stol (StolID, StolNr, RadNr, Område, SalID) VALUES (206, 8, 2, 'Balkong', 2);
INSERT INTO Stol (StolID, StolNr, RadNr, Område, SalID) VALUES (207, 9, 2, 'Balkong', 2);
INSERT INTO Stol (StolID, StolNr, RadNr, Område, SalID) VALUES (208, 10, 2, 'Balkong', 2);
INSERT INTO Stol (StolID, StolNr, RadNr, Område, SalID) VALUES (209, 11, 2, 'Balkong', 2);
INSERT INTO Stol (StolID, StolNr, RadNr, Område, SalID) VALUES (210, 12, 2, 'Balkong', 2);
INSERT INTO Stol (StolID, StolNr, RadNr, Område, SalID) VALUES (211, 13, 2, 'Balkong', 2);
INSERT INTO Stol (StolID, StolNr, RadNr, Område, SalID) VALUES (212, 14, 2, 'Balkong', 2);
INSERT INTO Stol (StolID, StolNr, RadNr, Område, SalID) VALUES (213, 15, 2, 'Balkong', 2);
INSERT INTO Stol (StolID, StolNr, RadNr, Område, SalID) VALUES (214, 16, 2, 'Balkong', 2);
INSERT INTO Stol (StolID, StolNr, RadNr, Område, SalID) VALUES (215, 17, 2, 'Balkong', 2);
INSERT INTO Stol (StolID, StolNr, RadNr, Område, SalID) VALUES (216, 18, 2, 'Balkong', 2);
INSERT INTO Stol (StolID, StolNr, RadNr, Område, SalID) VALUES (217, 19, 2, 'Balkong', 2);
INSERT INTO Stol (StolID, StolNr, RadNr, Område, SalID) VALUES (218, 20, 2, 'Balkong', 2);
INSERT INTO Stol (StolID, StolNr, RadNr, Område, SalID) VALUES (219, 21, 2, 'Balkong', 2);
INSERT INTO Stol (StolID, StolNr, RadNr, Område, SalID) VALUES (220, 22, 2, 'Balkong', 2);
INSERT INTO Stol (StolID, StolNr, RadNr, Område, SalID) VALUES (221, 23, 2, 'Balkong', 2);
INSERT INTO Stol (StolID, StolNr, RadNr, Område, SalID) VALUES (222, 24, 2, 'Balkong', 2);
INSERT INTO Stol (StolID, StolNr, RadNr, Område, SalID) VALUES (223, 25, 2, 'Balkong', 2);
INSERT INTO Stol (StolID, StolNr, RadNr, Område, SalID) VALUES (224, 26, 2, 'Balkong', 2);
INSERT INTO Stol (StolID, StolNr, RadNr, Område, SalID) VALUES (225, 27, 2, 'Balkong', 2);
INSERT INTO Stol (StolID, StolNr, RadNr, Område, SalID) VALUES (226, 1, 3, 'Balkong', 2);
INSERT INTO Stol (StolID, StolNr, RadNr, Område, SalID) VALUES (227, 2, 3, 'Balkong', 2);
INSERT INTO Stol (StolID, StolNr, RadNr, Område, SalID) VALUES (228, 3, 3, 'Balkong', 2);
INSERT INTO Stol (StolID, StolNr, RadNr, Område, SalID) VALUES (229, 4, 3, 'Balkong', 2);
INSERT INTO Stol (StolID, StolNr, RadNr, Område, SalID) VALUES (230, 5, 3, 'Balkong', 2);
INSERT INTO Stol (StolID, StolNr, RadNr, Område, SalID) VALUES (231, 6, 3, 'Balkong', 2);
INSERT INTO Stol (StolID, StolNr, RadNr, Område, SalID) VALUES (232, 7, 3, 'Balkong', 2);
INSERT INTO Stol (StolID, StolNr, RadNr, Område, SalID) VALUES (233, 8, 3, 'Balkong', 2);
INSERT INTO Stol (StolID, StolNr, RadNr, Område, SalID) VALUES (234, 9, 3, 'Balkong', 2);
INSERT INTO Stol (StolID, StolNr, RadNr, Område, SalID) VALUES (235, 10, 3, 'Balkong', 2);
INSERT INTO Stol (StolID, StolNr, RadNr, Område, SalID) VALUES (236, 11, 3, 'Balkong', 2);
INSERT INTO Stol (StolID, StolNr, RadNr, Område, SalID) VALUES (237, 12, 3, 'Balkong', 2);
INSERT INTO Stol (StolID, StolNr, RadNr, Område, SalID) VALUES (238, 13, 3, 'Balkong', 2);
INSERT INTO Stol (StolID, StolNr, RadNr, Område, SalID) VALUES (239, 14, 3, 'Balkong', 2);
INSERT INTO Stol (StolID, StolNr, RadNr, Område, SalID) VALUES (240, 15, 3, 'Balkong', 2);
INSERT INTO Stol (StolID, StolNr, RadNr, Område, SalID) VALUES (241, 16, 3, 'Balkong', 2);
INSERT INTO Stol (StolID, StolNr, RadNr, Område, SalID) VALUES (242, 17, 3, 'Balkong', 2);
INSERT INTO Stol (StolID, StolNr, RadNr, Område, SalID) VALUES (243, 18, 3, 'Balkong', 2);
INSERT INTO Stol (StolID, StolNr, RadNr, Område, SalID) VALUES (244, 19, 3, 'Balkong', 2);
INSERT INTO Stol (StolID, StolNr, RadNr, Område, SalID) VALUES (245, 20, 3, 'Balkong', 2);
INSERT INTO Stol (StolID, StolNr, RadNr, Område, SalID) VALUES (246, 21, 3, 'Balkong', 2);
INSERT INTO Stol (StolID, StolNr, RadNr, Område, SalID) VALUES (247, 22, 3, 'Balkong', 2);
INSERT INTO Stol (StolID, StolNr, RadNr, Område, SalID) VALUES (248, 1, 4, 'Balkong', 2);
INSERT INTO Stol (StolID, StolNr, RadNr, Område, SalID) VALUES (249, 2, 4, 'Balkong', 2);
INSERT INTO Stol (StolID, StolNr, RadNr, Område, SalID) VALUES (250, 3, 4, 'Balkong', 2);
INSERT INTO Stol (StolID, StolNr, RadNr, Område, SalID) VALUES (251, 4, 4, 'Balkong', 2);
INSERT INTO Stol (StolID, StolNr, RadNr, Område, SalID) VALUES (252, 5, 4, 'Balkong', 2);
INSERT INTO Stol (StolID, StolNr, RadNr, Område, SalID) VALUES (253, 6, 4, 'Balkong', 2);
INSERT INTO Stol (StolID, StolNr, RadNr, Område, SalID) VALUES (254, 7, 4, 'Balkong', 2);
INSERT INTO Stol (StolID, StolNr, RadNr, Område, SalID) VALUES (255, 8, 4, 'Balkong', 2);
INSERT INTO Stol (StolID, StolNr, RadNr, Område, SalID) VALUES (256, 9, 4, 'Balkong', 2);
INSERT INTO Stol (StolID, StolNr, RadNr, Område, SalID) VALUES (257, 10, 4, 'Balkong', 2);
INSERT INTO Stol (StolID, StolNr, RadNr, Område, SalID) VALUES (258, 11, 4, 'Balkong', 2);
INSERT INTO Stol (StolID, StolNr, RadNr, Område, SalID) VALUES (259, 12, 4, 'Balkong', 2);
INSERT INTO Stol (StolID, StolNr, RadNr, Område, SalID) VALUES (260, 13, 4, 'Balkong', 2);
INSERT INTO Stol (StolID, StolNr, RadNr, Område, SalID) VALUES (261, 14, 4, 'Balkong', 2);
INSERT INTO Stol (StolID, StolNr, RadNr, Område, SalID) VALUES (262, 15, 4, 'Balkong', 2);
INSERT INTO Stol (StolID, StolNr, RadNr, Område, SalID) VALUES (263, 16, 4, 'Balkong', 2);
INSERT INTO Stol (StolID, StolNr, RadNr, Område, SalID) VALUES (264, 17, 4, 'Balkong', 2);

INSERT INTO Stol (StolID, StolNr, RadNr, Område, SalID) VALUES (265, 1, 1, 'Galleri', 2);
INSERT INTO Stol (StolID, StolNr, RadNr, Område, SalID) VALUES (266, 2, 1, 'Galleri', 2);
INSERT INTO Stol (StolID, StolNr, RadNr, Område, SalID) VALUES (267, 3, 1, 'Galleri', 2);
INSERT INTO Stol (StolID, StolNr, RadNr, Område, SalID) VALUES (268, 4, 1, 'Galleri', 2);
INSERT INTO Stol (StolID, StolNr, RadNr, Område, SalID) VALUES (269, 5, 1, 'Galleri', 2);
INSERT INTO Stol (StolID, StolNr, RadNr, Område, SalID) VALUES (270, 6, 1, 'Galleri', 2);
INSERT INTO Stol (StolID, StolNr, RadNr, Område, SalID) VALUES (271, 7, 1, 'Galleri', 2);
INSERT INTO Stol (StolID, StolNr, RadNr, Område, SalID) VALUES (272, 8, 1, 'Galleri', 2);
INSERT INTO Stol (StolID, StolNr, RadNr, Område, SalID) VALUES (273, 9, 1, 'Galleri', 2);
INSERT INTO Stol (StolID, StolNr, RadNr, Område, SalID) VALUES (274, 10, 1, 'Galleri', 2);
INSERT INTO Stol (StolID, StolNr, RadNr, Område, SalID) VALUES (275, 11, 1, 'Galleri', 2);
INSERT INTO Stol (StolID, StolNr, RadNr, Område, SalID) VALUES (276, 12, 1, 'Galleri', 2);
INSERT INTO Stol (StolID, StolNr, RadNr, Område, SalID) VALUES (277, 13, 1, 'Galleri', 2);
INSERT INTO Stol (StolID, StolNr, RadNr, Område, SalID) VALUES (278, 14, 1, 'Galleri', 2);
INSERT INTO Stol (StolID, StolNr, RadNr, Område, SalID) VALUES (279, 15, 1, 'Galleri', 2);
INSERT INTO Stol (StolID, StolNr, RadNr, Område, SalID) VALUES (280, 16, 1, 'Galleri', 2);
INSERT INTO Stol (StolID, StolNr, RadNr, Område, SalID) VALUES (281, 17, 1, 'Galleri', 2);
INSERT INTO Stol (StolID, StolNr, RadNr, Område, SalID) VALUES (282, 18, 1, 'Galleri', 2);
INSERT INTO Stol (StolID, StolNr, RadNr, Område, SalID) VALUES (283, 19, 1, 'Galleri', 2);
INSERT INTO Stol (StolID, StolNr, RadNr, Område, SalID) VALUES (284, 20, 1, 'Galleri', 2);
INSERT INTO Stol (StolID, StolNr, RadNr, Område, SalID) VALUES (285, 21, 1, 'Galleri', 2);
INSERT INTO Stol (StolID, StolNr, RadNr, Område, SalID) VALUES (286, 22, 1, 'Galleri', 2);
INSERT INTO Stol (StolID, StolNr, RadNr, Område, SalID) VALUES (287, 23, 1, 'Galleri', 2);
INSERT INTO Stol (StolID, StolNr, RadNr, Område, SalID) VALUES (288, 24, 1, 'Galleri', 2);
INSERT INTO Stol (StolID, StolNr, RadNr, Område, SalID) VALUES (289, 25, 1, 'Galleri', 2);
INSERT INTO Stol (StolID, StolNr, RadNr, Område, SalID) VALUES (290, 26, 1, 'Galleri', 2);
INSERT INTO Stol (StolID, StolNr, RadNr, Område, SalID) VALUES (291, 27, 1, 'Galleri', 2);
INSERT INTO Stol (StolID, StolNr, RadNr, Område, SalID) VALUES (292, 28, 1, 'Galleri', 2);
INSERT INTO Stol (StolID, StolNr, RadNr, Område, SalID) VALUES (293, 29, 1, 'Galleri', 2);
INSERT INTO Stol (StolID, StolNr, RadNr, Område, SalID) VALUES (294, 30, 1, 'Galleri', 2);
INSERT INTO Stol (StolID, StolNr, RadNr, Område, SalID) VALUES (295, 31, 1, 'Galleri', 2);
INSERT INTO Stol (StolID, StolNr, RadNr, Område, SalID) VALUES (296, 32, 1, 'Galleri', 2);
INSERT INTO Stol (StolID, StolNr, RadNr, Område, SalID) VALUES (297, 33, 1, 'Galleri', 2);
INSERT INTO Stol (StolID, StolNr, RadNr, Område, SalID) VALUES (298, 1, 2, 'Galleri', 2);
INSERT INTO Stol (StolID, StolNr, RadNr, Område, SalID) VALUES (299, 2, 2, 'Galleri', 2);
INSERT INTO Stol (StolID, StolNr, RadNr, Område, SalID) VALUES (300, 3, 2, 'Galleri', 2);
INSERT INTO Stol (StolID, StolNr, RadNr, Område, SalID) VALUES (301, 4, 2, 'Galleri', 2);
INSERT INTO Stol (StolID, StolNr, RadNr, Område, SalID) VALUES (302, 5, 2, 'Galleri', 2);
INSERT INTO Stol (StolID, StolNr, RadNr, Område, SalID) VALUES (303, 6, 2, 'Galleri', 2);
INSERT INTO Stol (StolID, StolNr, RadNr, Område, SalID) VALUES (304, 7, 2, 'Galleri', 2);
INSERT INTO Stol (StolID, StolNr, RadNr, Område, SalID) VALUES (305, 8, 2, 'Galleri', 2);
INSERT INTO Stol (StolID, StolNr, RadNr, Område, SalID) VALUES (306, 9, 2, 'Galleri', 2);
INSERT INTO Stol (StolID, StolNr, RadNr, Område, SalID) VALUES (307, 10, 2, 'Galleri', 2);
INSERT INTO Stol (StolID, StolNr, RadNr, Område, SalID) VALUES (308, 11, 2, 'Galleri', 2);
INSERT INTO Stol (StolID, StolNr, RadNr, Område, SalID) VALUES (309, 12, 2, 'Galleri', 2);
INSERT INTO Stol (StolID, StolNr, RadNr, Område, SalID) VALUES (310, 13, 2, 'Galleri', 2);
INSERT INTO Stol (StolID, StolNr, RadNr, Område, SalID) VALUES (311, 14, 2, 'Galleri', 2);
INSERT INTO Stol (StolID, StolNr, RadNr, Område, SalID) VALUES (312, 15, 2, 'Galleri', 2);
INSERT INTO Stol (StolID, StolNr, RadNr, Område, SalID) VALUES (313, 16, 2, 'Galleri', 2);
INSERT INTO Stol (StolID, StolNr, RadNr, Område, SalID) VALUES (314, 17, 2, 'Galleri', 2);
INSERT INTO Stol (StolID, StolNr, RadNr, Område, SalID) VALUES (315, 18, 2, 'Galleri', 2);
INSERT INTO Stol (StolID, StolNr, RadNr, Område, SalID) VALUES (316, 1, 3, 'Galleri', 2);
INSERT INTO Stol (StolID, StolNr, RadNr, Område, SalID) VALUES (317, 2, 3, 'Galleri', 2);
INSERT INTO Stol (StolID, StolNr, RadNr, Område, SalID) VALUES (318, 3, 3, 'Galleri', 2);
INSERT INTO Stol (StolID, StolNr, RadNr, Område, SalID) VALUES (319, 4, 3, 'Galleri', 2);
INSERT INTO Stol (StolID, StolNr, RadNr, Område, SalID) VALUES (320, 5, 3, 'Galleri', 2);
INSERT INTO Stol (StolID, StolNr, RadNr, Område, SalID) VALUES (321, 6, 3, 'Galleri', 2);
INSERT INTO Stol (StolID, StolNr, RadNr, Område, SalID) VALUES (322, 7, 3, 'Galleri', 2);
INSERT INTO Stol (StolID, StolNr, RadNr, Område, SalID) VALUES (323, 8, 3, 'Galleri', 2);
INSERT INTO Stol (StolID, StolNr, RadNr, Område, SalID) VALUES (324, 9, 3, 'Galleri', 2);
INSERT INTO Stol (StolID, StolNr, RadNr, Område, SalID) VALUES (325, 10, 3, 'Galleri', 2);
INSERT INTO Stol (StolID, StolNr, RadNr, Område, SalID) VALUES (326, 11, 3, 'Galleri', 2);
INSERT INTO Stol (StolID, StolNr, RadNr, Område, SalID) VALUES (327, 12, 3, 'Galleri', 2);
INSERT INTO Stol (StolID, StolNr, RadNr, Område, SalID) VALUES (328, 13, 3, 'Galleri', 2);
INSERT INTO Stol (StolID, StolNr, RadNr, Område, SalID) VALUES (329, 14, 3, 'Galleri', 2);
INSERT INTO Stol (StolID, StolNr, RadNr, Område, SalID) VALUES (330, 15, 3, 'Galleri', 2);
INSERT INTO Stol (StolID, StolNr, RadNr, Område, SalID) VALUES (331, 16, 3, 'Galleri', 2);
INSERT INTO Stol (StolID, StolNr, RadNr, Område, SalID) VALUES (332, 17, 3, 'Galleri', 2);

INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (333, 1, 1, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (334, 2, 1, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (335, 3, 1, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (336, 4, 1, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (337, 5, 1, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (338, 6, 1, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (339, 7, 1, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (340, 8, 1, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (341, 9, 1, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (342, 10, 1, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (343, 11, 1, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (344, 12, 1, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (345, 13, 1, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (346, 14, 1, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (347, 15, 1, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (348, 16, 1, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (349, 17, 1, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (350, 18, 1, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (351, 19, 1, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (352, 20, 1, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (353, 21, 1, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (354, 22, 1, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (355, 23, 1, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (356, 24, 1, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (357, 25, 1, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (358, 26, 1, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (359, 27, 1, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (360, 28, 1, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (361, 29, 2, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (362, 30, 2, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (363, 31, 2, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (364, 32, 2, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (365, 33, 2, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (366, 34, 2, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (367, 35, 2, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (368, 36, 2, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (369, 37, 2, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (370, 38, 2, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (371, 39, 2, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (372, 40, 2, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (373, 41, 2, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (374, 42, 2, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (375, 43, 2, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (376, 44, 2, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (377, 45, 2, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (378, 46, 2, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (379, 47, 2, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (380, 48, 2, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (381, 49, 2, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (382, 50, 2, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (383, 51, 2, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (384, 52, 2, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (385, 53, 2, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (386, 54, 2, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (387, 55, 2, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (388, 56, 2, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (389, 57, 3, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (390, 58, 3, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (391, 59, 3, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (392, 60, 3, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (393, 61, 3, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (394, 62, 3, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (395, 63, 3, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (396, 64, 3, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (397, 65, 3, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (398, 66, 3, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (399, 67, 3, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (400, 68, 3, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (401, 69, 3, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (402, 70, 3, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (403, 71, 3, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (404, 72, 3, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (405, 73, 3, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (406, 74, 3, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (407, 75, 3, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (408, 76, 3, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (409, 77, 3, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (410, 78, 3, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (411, 79, 3, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (412, 80, 3, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (413, 81, 3, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (414, 82, 3, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (415, 83, 3, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (416, 84, 3, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (417, 85, 4, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (418, 86, 4, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (419, 87, 4, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (420, 88, 4, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (421, 89, 4, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (422, 90, 4, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (423, 91, 4, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (424, 92, 4, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (425, 93, 4, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (426, 94, 4, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (427, 95, 4, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (428, 96, 4, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (429, 97, 4, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (430, 98, 4, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (431, 99, 4, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (432, 100, 4, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (433, 101, 4, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (434, 102, 4, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (435, 103, 4, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (436, 104, 4, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (437, 105, 4, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (438, 106, 4, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (439, 107, 4, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (440, 108, 4, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (441, 109, 4, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (442, 110, 4, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (443, 111, 4, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (444, 112, 4, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (445, 113, 5, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (446, 114, 5, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (447, 115, 5, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (448, 116, 5, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (449, 117, 5, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (450, 118, 5, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (451, 119, 5, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (452, 120, 5, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (453, 121, 5, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (454, 122, 5, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (455, 123, 5, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (456, 124, 5, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (457, 125, 5, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (458, 126, 5, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (459, 127, 5, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (460, 128, 5, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (461, 129, 5, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (462, 130, 5, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (463, 131, 5, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (464, 132, 5, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (465, 133, 5, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (466, 134, 5, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (467, 135, 5, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (468, 136, 5, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (469, 137, 5, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (470, 138, 5, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (471, 139, 5, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (472, 140, 5, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (473, 141, 6, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (474, 142, 6, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (475, 143, 6, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (476, 144, 6, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (477, 145, 6, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (478, 146, 6, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (479, 147, 6, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (480, 148, 6, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (481, 149, 6, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (482, 150, 6, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (483, 151, 6, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (484, 152, 6, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (485, 153, 6, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (486, 154, 6, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (487, 155, 6, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (488, 156, 6, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (489, 157, 6, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (490, 158, 6, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (491, 159, 6, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (492, 160, 6, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (493, 161, 6, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (494, 162, 6, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (495, 163, 6, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (496, 164, 6, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (497, 165, 6, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (498, 166, 6, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (499, 167, 6, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (500, 168, 6, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (501, 169, 7, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (502, 170, 7, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (503, 171, 7, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (504, 172, 7, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (505, 173, 7, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (506, 174, 7, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (507, 175, 7, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (508, 176, 7, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (509, 177, 7, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (510, 178, 7, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (511, 179, 7, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (512, 180, 7, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (513, 181, 7, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (514, 182, 7, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (515, 183, 7, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (516, 184, 7, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (517, 185, 7, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (518, 186, 7, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (519, 187, 7, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (520, 188, 7, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (521, 189, 7, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (522, 190, 7, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (523, 191, 7, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (524, 192, 7, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (525, 193, 7, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (526, 194, 7, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (527, 195, 7, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (528, 196, 7, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (529, 197, 8, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (530, 198, 8, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (531, 199, 8, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (532, 200, 8, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (533, 201, 8, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (534, 202, 8, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (535, 203, 8, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (536, 204, 8, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (537, 205, 8, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (538, 206, 8, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (539, 207, 8, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (540, 208, 8, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (541, 209, 8, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (542, 210, 8, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (543, 211, 8, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (544, 212, 8, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (545, 213, 8, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (546, 214, 8, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (547, 215, 8, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (548, 216, 8, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (549, 217, 8, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (550, 218, 8, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (551, 219, 8, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (552, 220, 8, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (553, 221, 8, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (554, 222, 8, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (555, 223, 8, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (556, 224, 8, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (557, 225, 9, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (558, 226, 9, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (559, 227, 9, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (560, 228, 9, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (561, 229, 9, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (562, 230, 9, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (563, 231, 9, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (564, 232, 9, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (565, 233, 9, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (566, 234, 9, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (567, 235, 9, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (568, 236, 9, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (569, 237, 9, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (570, 238, 9, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (571, 239, 9, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (572, 240, 9, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (573, 241, 9, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (574, 242, 9, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (575, 243, 9, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (576, 244, 9, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (577, 245, 9, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (578, 246, 9, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (579, 247, 9, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (580, 248, 9, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (581, 249, 9, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (582, 250, 9, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (583, 251, 9, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (584, 252, 9, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (585, 253, 10, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (586, 254, 10, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (587, 255, 10, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (588, 256, 10, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (589, 257, 10, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (590, 258, 10, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (591, 259, 10, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (592, 260, 10, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (593, 261, 10, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (594, 262, 10, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (595, 263, 10, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (596, 264, 10, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (597, 265, 10, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (598, 266, 10, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (599, 267, 10, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (600, 268, 10, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (601, 269, 10, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (602, 270, 10, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (603, 271, 10, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (604, 272, 10, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (605, 273, 10, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (606, 274, 10, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (607, 275, 10, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (608, 276, 10, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (609, 277, 10, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (610, 278, 10, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (611, 279, 10, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (612, 280, 10, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (613, 281, 11, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (614, 282, 11, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (615, 283, 11, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (616, 284, 11, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (617, 285, 11, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (618, 286, 11, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (619, 287, 11, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (620, 288, 11, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (621, 289, 11, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (622, 290, 11, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (623, 291, 11, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (624, 292, 11, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (625, 293, 11, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (626, 294, 11, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (627, 295, 11, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (628, 296, 11, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (629, 297, 11, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (630, 298, 11, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (631, 299, 11, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (632, 300, 11, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (633, 301, 11, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (634, 302, 11, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (635, 303, 11, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (636, 304, 11, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (637, 305, 11, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (638, 306, 11, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (639, 307, 11, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (640, 308, 11, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (641, 309, 12, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (642, 310, 12, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (643, 311, 12, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (644, 312, 12, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (645, 313, 12, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (646, 314, 12, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (647, 315, 12, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (648, 316, 12, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (649, 317, 12, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (650, 318, 12, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (651, 319, 12, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (652, 320, 12, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (653, 321, 12, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (654, 322, 12, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (655, 323, 12, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (656, 324, 12, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (657, 325, 12, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (658, 326, 12, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (659, 327, 12, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (660, 328, 12, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (661, 329, 12, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (662, 330, 12, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (663, 331, 12, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (664, 332, 12, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (665, 333, 12, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (666, 334, 12, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (667, 335, 12, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (668, 336, 12, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (669, 337, 13, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (670, 338, 13, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (671, 339, 13, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (672, 340, 13, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (673, 341, 13, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (674, 342, 13, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (675, 343, 13, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (676, 344, 13, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (677, 345, 13, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (678, 346, 13, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (679, 347, 13, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (680, 348, 13, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (681, 349, 13, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (682, 350, 13, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (683, 351, 13, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (684, 352, 13, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (685, 353, 13, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (686, 354, 13, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (687, 355, 13, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (688, 356, 13, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (689, 357, 13, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (690, 358, 13, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (691, 359, 13, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (692, 360, 13, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (693, 361, 13, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (694, 362, 13, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (695, 363, 13, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (696, 364, 13, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (697, 365, 14, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (698, 366, 14, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (699, 367, 14, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (700, 368, 14, 'Parkett', 1);



INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (701, 369, 14, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (702, 370, 14, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (703, 371, 14, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (704, 372, 14, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (705, 373, 14, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (706, 374, 14, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (707, 375, 14, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (708, 376, 14, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (709, 377, 14, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (710, 378, 14, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (711, 379, 14, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (712, 380, 14, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (713, 381, 14, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (714, 382, 14, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (715, 383, 14, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (716, 384, 14, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (717, 385, 14, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (718, 386, 14, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (719, 387, 14, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (720, 388, 14, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (721, 389, 14, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (722, 390, 14, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (723, 391, 14, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (724, 392, 14, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (725, 393, 15, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (726, 394, 15, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (727, 395, 15, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (728, 396, 15, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (729, 397, 15, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (730, 398, 15, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (731, 399, 15, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (732, 400, 15, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (733, 401, 15, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (734, 402, 15, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (735, 403, 15, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (736, 404, 15, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (737, 405, 15, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (738, 406, 15, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (739, 407, 15, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (740, 408, 15, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (741, 409, 15, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (742, 410, 15, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (743, 411, 15, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (744, 412, 15, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (745, 413, 15, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (746, 414, 15, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (747, 415, 15, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (748, 416, 15, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (749, 417, 15, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (750, 418, 15, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (751, 419, 15, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (752, 420, 15, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (753, 421, 16, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (754, 422, 16, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (755, 423, 16, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (756, 424, 16, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (757, 425, 16, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (758, 426, 16, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (759, 427, 16, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (760, 428, 16, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (761, 429, 16, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (762, 430, 16, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (763, 431, 16, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (764, 432, 16, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (765, 433, 16, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (766, 434, 16, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (767, 435, 16, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (768, 436, 16, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (769, 437, 16, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (770, 438, 16, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (771, 439, 16, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (772, 440, 16, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (773, 441, 16, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (774, 442, 16, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (775, 443, 16, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (776, 444, 16, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (777, 445, 16, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (778, 446, 16, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (779, 447, 16, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (780, 448, 16, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (781, 449, 17, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (782, 450, 17, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (783, 451, 17, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (784, 452, 17, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (785, 453, 17, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (786, 454, 17, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (787, 455, 17, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (788, 456, 17, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (789, 457, 17, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (790, 458, 17, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (791, 459, 17, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (792, 460, 17, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (793, 461, 17, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (794, 462, 17, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (795, 463, 17, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (796, 464, 17, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (797, 465, 17, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (798, 466, 17, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (803, 471, 17, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (804, 472, 17, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (805, 473, 17, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (806, 474, 17, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (807, 475, 17, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (808, 476, 17, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (809, 477, 18, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (810, 478, 18, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (811, 479, 18, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (812, 480, 18, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (813, 481, 18, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (814, 482, 18, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (815, 483, 18, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (816, 484, 18, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (817, 485, 18, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (818, 486, 18, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (819, 487, 18, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (820, 488, 18, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (821, 489, 18, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (822, 490, 18, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (823, 491, 18, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (824, 492, 18, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (825, 493, 18, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (826, 494, 18, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (827, 495, 18, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (828, 496, 18, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (829, 497, 18, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (830, 498, 18, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (831, 499, 18, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (832, 500, 18, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (833, 501, 18, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (834, 502, 18, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (835, 503, 18, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (836, 504, 18, 'Parkett', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (837, 505, 1, 'Galleri', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (838, 506, 1, 'Galleri', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (839, 507, 1, 'Galleri', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (840, 508, 1, 'Galleri', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (841, 509, 1, 'Galleri', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (842, 510, 2, 'Galleri', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (843, 511, 2, 'Galleri', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (844, 512, 2, 'Galleri', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (845, 513, 2, 'Galleri', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (846, 514, 2, 'Galleri', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (847, 515, 3, 'Galleri', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (848, 516, 3, 'Galleri', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (849, 517, 3, 'Galleri', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (850, 518, 3, 'Galleri', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (851, 519, 3, 'Galleri', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (852, 520, 4, 'Galleri', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (853, 521, 4, 'Galleri', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (854, 522, 4, 'Galleri', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (855, 523, 4, 'Galleri', 1);
INSERT INTO Stol (StolID, StolNr, RadNr, Omr�de, SalID) VALUES (856, 524, 4, 'Galleri', 1);


-- BillettType
INSERT INTO BillettType (BillettTypeID, Gruppestatus, KundeType) VALUES (1, False, 'Ordinær');
INSERT INTO BillettType (BillettTypeID, Gruppestatus, KundeType) VALUES (2, False, 'Honnør');
INSERT INTO BillettType (BillettTypeID, Gruppestatus, KundeType) VALUES (3, False, 'Student');
INSERT INTO BillettType (BillettTypeID, Gruppestatus, KundeType) VALUES (4, False, 'Barn');
INSERT INTO BillettType (BillettTypeID, Gruppestatus, KundeType) VALUES (5, True, 'Ordinær');
INSERT INTO BillettType (BillettTypeID, Gruppestatus, KundeType) VALUES (6, True, 'Honnør');


-- Pris
INSERT INTO Pris (BillettTypeID, Tittel, Pris) VALUES (1, 'Kongsemnene', 450);
INSERT INTO Pris (BillettTypeID, Tittel, Pris) VALUES (2, 'Kongsemnene', 380);
INSERT INTO Pris (BillettTypeID, Tittel, Pris) VALUES (3, 'Kongsemnene', 280);
INSERT INTO Pris (BillettTypeID, Tittel, Pris) VALUES (5, 'Kongsemnene', 420);
INSERT INTO Pris (BillettTypeID, Tittel, Pris) VALUES (6, 'Kongsemnene', 360);
INSERT INTO Pris (BillettTypeID, Tittel, Pris) VALUES (1, 'Størst av alt er kjærligheten', 350);
INSERT INTO Pris (BillettTypeID, Tittel, Pris) VALUES (2, 'Størst av alt er kjærligheten', 300);
INSERT INTO Pris (BillettTypeID, Tittel, Pris) VALUES (3, 'Størst av alt er kjærligheten', 220);
INSERT INTO Pris (BillettTypeID, Tittel, Pris) VALUES (4, 'Størst av alt er kjærligheten', 220);
INSERT INTO Pris (BillettTypeID, Tittel, Pris) VALUES (5, 'Størst av alt er kjærligheten', 320);
INSERT INTO Pris (BillettTypeID, Tittel, Pris) VALUES (6, 'Størst av alt er kjærligheten', 270);



-- Kunde
INSERT INTO Kunde (KundeID, TlfNr, Fornavn, Etternavn, Adresse, KundeType) VALUES ();

-- Billett
INSERT INTO Billett (BillettID, StolID, Tittel, Dato, BillettTypeID) VALUES ();

-- Billetkjøp
INSERT INTO Billetkjøp (KundeID, BillettID, Dato, Tid) VALUES ();


